/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { NodeId } from './nodeId';

export type AddImageLayerParams = {
/**
 * Optional text node to bind this custom image layer as its repair
 * result. Omit for a normal free image layer.
 */
repairText?: null | NodeId;
};
