/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { AiModelsConfig } from './aiModelsConfig';
import type { DataConfig } from './dataConfig';
import type { HttpConfig } from './httpConfig';
import type { PipelineConfig } from './pipelineConfig';
import type { ProviderConfig } from './providerConfig';

export interface AppConfig {
  ai_models?: AiModelsConfig;
  data?: DataConfig;
  http?: HttpConfig;
  pipeline?: PipelineConfig;
  providers?: ProviderConfig[];
}
