/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { FontBucket } from './fontBucket';

export interface FontPolicy {
  buckets?: { [key: string]: FontBucket };
  /** @nullable */
  fallbackFont?: string | null;
}
