/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { FontReviewItemStatus } from './fontReviewItemStatus';
import type { FontReviewPriority } from './fontReviewPriority';
import type { NodeId } from './nodeId';

export interface FontReviewQueueItem {
  id: string;
  blockId: NodeId;
  profileId: string;
  profileVersion: number;
  styleGroupId: string;
  reviewPriority: FontReviewPriority;
  riskReasons?: string[];
  suggestedAction?: string;
  status?: FontReviewItemStatus;
}
