/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { FontStyleRole } from './fontStyleRole';
import type { NodeId } from './nodeId';

export interface FontStyleGroup {
  id: string;
  label: string;
  role: FontStyleRole;
  description?: string;
  sourceCategories?: string[];
  preserveSourceStyle?: boolean;
  targetBucket: string;
  representativeBlocks?: NodeId[];
  confidence?: number;
  needsReview?: boolean;
  riskReasons?: string[];
  distinguishingFeatures?: string[];
  possibleConfusions?: string[];
}
