/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { FontProfileChange } from './fontProfileChange';
import type { FontProfileRisk } from './fontProfileRisk';
import type { FontProfileStatus } from './fontProfileStatus';
import type { FontReviewState } from './fontReviewState';
import type { FontStyleGroup } from './fontStyleGroup';

export interface FontStyleProfile {
  id: string;
  version: number;
  status: FontProfileStatus;
  reviewState: FontReviewState;
  source: string;
  profileConfidence: number;
  profileRisks?: FontProfileRisk[];
  styleGroups?: FontStyleGroup[];
  previousVersions?: string[];
  changeLog?: FontProfileChange[];
}
