/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface FontWorkflowTrace {
  candidateFonts?: string[];
  notes?: string[];
  /** @nullable */
  primaryCategory?: string | null;
  /** @nullable */
  secondaryCategory?: string | null;
  /** @nullable */
  selectedFont?: string | null;
}
