/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { NodeId } from './nodeId';

export interface FontProfileChange {
  version: number;
  change: string;
  affectedBlocks?: NodeId[];
}
