/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { FontProfileStatus } from './fontProfileStatus';
import type { FontReviewPriority } from './fontReviewPriority';
import type { FontStyleRole } from './fontStyleRole';
import type { NamedFontPrediction } from './namedFontPrediction';

export interface FontWorkflowTrace {
  candidateFonts?: string[];
  notes?: string[];
  /** @nullable */
  primaryCategory?: string | null;
  /** @nullable */
  secondaryCategory?: string | null;
  /** @nullable */
  selectedFont?: string | null;
  /** @nullable */
  provider?: string | null;
  /** @nullable */
  profileId?: string | null;
  /** @nullable */
  profileVersion?: number | null;
  /** @nullable */
  profileStatus?: null | FontProfileStatus;
  yuzumarkerCandidates?: NamedFontPrediction[];
  /** @nullable */
  textRole?: null | FontStyleRole;
  /** @nullable */
  styleGroupId?: string | null;
  /** @nullable */
  sourcePrimaryCategory?: string | null;
  /** @nullable */
  sourceSecondaryCategory?: string | null;
  /** @nullable */
  sourceWeight?: string | null;
  /** @nullable */
  sourceEmphasis?: string | null;
  /** @nullable */
  preserveSourceStyle?: boolean | null;
  /** @nullable */
  recommendedFontBucket?: string | null;
  /** @nullable */
  policy?: string | null;
  /** @nullable */
  confidence?: number | null;
  /** @nullable */
  autoApplied?: boolean | null;
  /** @nullable */
  needsReview?: boolean | null;
  reviewPriority?: FontReviewPriority;
  riskReasons?: string[];
  manualOverride?: boolean;
  previousFontFamilies?: string[];
  /** @nullable */
  previousFontSize?: number | null;
}
