/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface ProjectSummary {
  /**
     * API URL for the first page source image, used by the client bookshelf
     * cover. Project summaries may describe projects that are not currently
     * open, so this is project-scoped instead of a session-scoped `BlobRef`.
     * @nullable
     */
  coverUrl?: string | null;
  /**
     * Stable identifier — the `.khrproj` directory basename (without the
     * extension). Clients address projects by this.
     */
  id: string;
  name: string;
  /**
     * Number of pages currently saved in the project scene.
     * @minimum 0
     */
  pageCount?: number;
  /**
     * Absolute filesystem path. Informational; clients never need to pass
     * it back in — they use `id`.
     */
  path: string;
  /**
     * Number of text blocks across all pages.
     * @minimum 0
     */
  textBlockCount?: number;
  /**
     * Last modification time of the project directory on disk (ms since
     * UNIX epoch). Used for "recent projects" ordering.
     * @minimum 0
     */
  updatedAtMs?: number;
}
