/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type TextWorkflowMode = typeof TextWorkflowMode[keyof typeof TextWorkflowMode];


export const TextWorkflowMode = {
  lettering: 'lettering',
  repair: 'repair',
} as const;
