/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type TextResultMode = typeof TextResultMode[keyof typeof TextResultMode];


export const TextResultMode = {
  lettering: 'lettering',
  repair: 'repair',
} as const;
